packageExtensions:
  "eslint-config-next@*":
    peerDependencies:
      eslint: "*"
  "@next/eslint-plugin-next@*":
    peerDependencies:
      eslint: "*"
  "react-day-picker@*":
    peerDependencies:
      date-fns: "*" 